language: generic
sudo: required
services:
  - docker

before_script:
  # AWS Preparation
  - openssl aes-256-cbc -K $encrypted_23c54cda1817_key -iv $encrypted_23c54cda1817_iv -in .env-chat.enc -out .env-chat -d
  - source ./.env-chat
  - openssl aes-256-cbc -K $encrypted_8e598197dea0_key -iv $encrypted_8e598197dea0_iv -in to-do-list-aws.pem.enc -out to-do-list-aws.pem -d # get encrypted pem
  - chmod 400 ./"$AWS_PEM" # chmod 400 to pem
  # preparing image
  - npm install
  - docker build -t "$DOCKER_USERNAME"/"$IMAGE" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/"$IMAGE"
  

script:
  - sudo scp -o StrictHostKeyChecking=no -i $AWS_PEM ./env-chat $AWS_HOST@$DEPLOY_HOST:$AWS_WORKDIR < interactive_login.in

after_script:
  # deploy
  - ssh -i -o StrictHostKeyChecking=no $AWS_PEM $AWS_HOST@$DEPLOY_HOST "bash -s < deploy-chat-aws.sh" #aws
